name: yako_theme_switch
description: Custom switch that looks good for changing the theme of the app
version: 1.0.0+1
repository: https://github.com/yako-dev/flutter-yako-theme-switch
issue_tracker: https://github.com/yako-dev/flutter-yako-theme-switch/issues

topics:
  - ui

screenshots:
  - description: "Switch gif animation"
    path: assets/showcase_animation.gif

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
